# Generated by Django 5.2.17 on 2026-09-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0003_team_discord_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="max_uses",
            field=models.PositiveIntegerField(default=0, verbose_name="최대 사용 횟수"),
        ),
        migrations.AddField(
            model_name="organization",
            name="settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="설정"),
        ),
    ]
