# Generated by Django 5.2.17 on 2026-09-28 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import orgs.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_apitoken_for_ai"),
        ("orgs", "0004_settings_and_discord_binding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("settings", "조직 설정"),
                            ("governance", "개발 거버넌스"),
                        ],
                        max_length=10,
                    ),
                ),
                ("base", models.JSONField()),
                ("proposed", models.JSONField()),
                ("reason", models.CharField(max_length=500, verbose_name="변경 이유")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "허용"),
                            ("rejected", "거절"),
                            ("stale", "무효"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="거절 사유"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=orgs.models._default_expiry),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="orgs.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.apitoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
