# Generated by Django 5.2.17 on 2026-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0005_changerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembership",
            name="is_lead",
            field=models.BooleanField(default=False, verbose_name="팀장"),
        ),
    ]
