# Generated by Django 5.2.17 on 2026-10-04 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0006_teammembership_is_lead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="discord_bot_permissions",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="discord_watch_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="discord_channel_managed",
            field=models.BooleanField(default=False, verbose_name="채널 자동 관리"),
        ),
        migrations.CreateModel(
            name="DiscordChannelAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=32)),
                ("discord_user_id", models.CharField(max_length=32)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "경고"),
                            ("allowed", "허용"),
                            ("gone", "사라짐"),
                            ("missing", "접근 없음"),
                        ],
                        default="open",
                        max_length=7,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.organization",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel_id", "discord_user_id"),
                        name="dcalert_channel_user",
                    )
                ],
            },
        ),
    ]
