# Generated by Django 5.2.17 on 2026-10-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0008_discord_member_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="dev_tools",
            field=models.BooleanField(default=True, verbose_name="개발 도구"),
        ),
        migrations.AddField(
            model_name="team",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="팀 화면 비공개"),
        ),
    ]
