# Generated by Django 5.2.17 on 2026-09-17 17:37

from django.db import migrations, models


def clear_default_label(apps, schema_editor):
    """아무도 고르지 않은 옛 기본값 "task"를 비운다.

    그 라벨을 쓰지 않는 저장소에서는 이슈가 한 건도 보이지 않았다. 일부러 task 라벨로
    거르던 곳은 저장소 탭에서 다시 넣으면 된다.
    """
    apps.get_model("github", "RepoConnection").objects.filter(import_label="task").update(
        import_label=""
    )


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0003_repoissue_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="repoconnection",
            name="issues_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="repoconnection",
            name="import_label",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.RunPython(clear_default_label, migrations.RunPython.noop),
    ]
