# Generated by Django 5.2.17 on 2026-10-03 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0004_repoconnection_issue_sync"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repoconnection",
            name="assignee_default",
        ),
    ]
