# Generated by Django 5.2.17 on 2026-10-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0005_remove_repoconnection_assignee_default"),
        ("projects", "0011_milestone_gh_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="repoconnection",
            name="rule_milestone",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repoconnection",
            name="rule_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="repoconnection",
            name="rule_sync",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="ci_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="ci_checks",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="ci_state",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="ci_url",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="head_sha",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="issue_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="pr_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="pr_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="review_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="review_state",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskgitlink",
            name="reviews",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="GitRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("url", models.CharField(max_length=300)),
                ("prerelease", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField()),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="github.repoconnection",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releases",
                        to="projects.milestone",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "tag"), name="gitrelease_conn_tag"
                    )
                ],
            },
        ),
    ]
