# Generated by Django 5.2.17 on 2026-10-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0006_round8"),
    ]

    operations = [
        migrations.AddField(
            model_name="repoconnection",
            name="discord_hook",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
