# Generated by Django 5.2.17 on 2026-09-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="설정"),
        ),
    ]
