# Generated by Django 5.2.17 on 2026-09-28 07:17

from django.db import migrations, models


def bot_tokens_are_not_ai(apps, schema_editor):
    # 기존 토큰은 더 엄격한 쪽(AI용)으로 둔다. 사람이 쓰던 스크립트는 사람용 토큰을 새로 받는다.
    # 봇 토큰만 사람 명령을 옮기므로 AI가 아니다.
    apps.get_model("accounts", "ApiToken").objects.filter(scope="bot").update(for_ai=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_oauthclient_oauthcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="for_ai",
            field=models.BooleanField(default=True, verbose_name="AI용"),
        ),
        migrations.RunPython(bot_tokens_are_not_ai, migrations.RunPython.noop),
    ]
