# Generated by Django 5.2.17 on 2026-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_apitoken_for_ai"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=10)),
                ("key", models.CharField(max_length=150)),
                ("failures", models.PositiveSmallIntegerField(default=0)),
                ("window_started_at", models.DateTimeField()),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "key"), name="loginlock_kind_key")
                ],
            },
        ),
    ]
