from pathlib import Path
import json

OUT = Path(__file__).parent
CSS = r'''
.concept-header{display:flex;align-items:center;justify-content:space-between;gap:var(--sp-4);padding:var(--sp-5) var(--sp-8);border-bottom:1px solid var(--c-line);background:var(--c-surface)}
.brand{display:flex;align-items:center;gap:var(--sp-4);font-weight:600}.brand img{width:94px;height:38px}.concept-header a{font-size:var(--fs-sm)}
.concept{padding:var(--sp-8);display:grid;grid-template-columns:200px minmax(0,1fr);gap:var(--sp-8)}
.index{align-self:start;position:sticky;top:var(--sp-6);display:flex;flex-direction:column;gap:var(--sp-1)}.index a{padding:var(--sp-3);color:var(--c-muted);text-decoration:none;border-radius:var(--r-md)}.index a:hover{background:var(--c-soft)}.index strong{padding:var(--sp-3);font-size:var(--fs-xs);color:var(--c-muted)}
.canvas{min-width:0}.page-head{margin-bottom:var(--sp-6)}.page-head h1{display:inline-block}.intro{color:var(--c-muted);margin-top:var(--sp-4);max-width:72ch}.chapter{margin-bottom:var(--sp-10);scroll-margin-top:var(--sp-6)}.chapter-head{display:flex;align-items:baseline;justify-content:space-between;gap:var(--sp-4);margin-bottom:var(--sp-4)}.chapter-head h2{font:var(--fs-2xl) var(--f-display)}.chapter-head span{font-size:var(--fs-xs);color:var(--c-muted)}
.context{background:var(--c-surface);border:1px solid var(--c-line);border-radius:var(--r-lg);padding:var(--sp-6);min-width:0}.context-head{display:flex;align-items:center;justify-content:space-between;gap:var(--sp-3);margin-bottom:var(--sp-5);flex-wrap:wrap}.context h3{font:var(--fs-2xl) var(--f-display);margin:0}.context-path{font-size:var(--fs-xs);color:var(--c-muted);margin-bottom:var(--sp-2)}
.task-layout{display:grid;grid-template-columns:minmax(0,1fr) 260px;gap:var(--sp-6)}.task-aside{border-left:1px solid var(--c-line);padding-left:var(--sp-6)}.task-aside dl{margin:0;display:grid;gap:var(--sp-4)}.task-aside dt{color:var(--c-muted);font-size:var(--fs-xs)}.task-aside dd{margin:var(--sp-1) 0 0}.task-aside .aside-note{border-top:1px solid var(--c-line);margin-top:var(--sp-6);padding-top:var(--sp-5);font-size:var(--fs-sm);color:var(--c-muted)}
.field-block{margin-bottom:var(--sp-5);min-width:0}.field-heading{display:flex;gap:var(--sp-3);align-items:center;justify-content:space-between;margin-bottom:var(--sp-2)}.field-label{font-size:var(--fs-sm);font-weight:600}.field-heading .state{font-size:var(--fs-xs);color:var(--c-muted)}.rationale{color:var(--c-muted);font-size:var(--fs-xs);margin:var(--sp-2) 0 0;line-height:1.6}.rationale b{font-weight:600;color:var(--c-ink)}
.edit-shell{border:1px solid var(--c-line);border-radius:var(--r-md);background:var(--c-surface);position:relative;min-width:0}.edit-shell:focus-within{border-color:var(--c-accent);box-shadow:0 0 0 3px var(--c-accent-soft)}.editor .ProseMirror{padding:var(--sp-4);min-height:110px}.field-block.short .editor .ProseMirror{min-height:76px}.field-block.long .editor .ProseMirror{min-height:280px}.field-block.manuscript .editor .ProseMirror{min-height:540px}.editor .ProseMirror:focus-visible{outline:0}.editor .ProseMirror p.is-editor-empty:first-child::before{color:var(--c-muted)}
.format-bar{display:flex;align-items:center;gap:var(--sp-1);padding:var(--sp-2);border-bottom:1px solid var(--c-line);flex-wrap:wrap}.format-bar button,.bubble button{border:0;background:transparent;color:var(--c-ink);border-radius:var(--r-sm);padding:var(--sp-2) var(--sp-3);min-height:36px;min-width:36px;font:inherit;font-size:var(--fs-sm);cursor:pointer}.format-bar button:hover,.bubble button:hover{background:var(--c-soft)}.format-bar button[aria-pressed=true],.bubble button[aria-pressed=true]{background:var(--c-accent-soft);color:var(--c-accent)}.format-bar .divider{height:20px;width:1px;background:var(--c-line);margin-inline:var(--sp-1)}.format-bar.bottom{border-top:1px solid var(--c-line);border-bottom:0;position:sticky;bottom:0;background:var(--c-surface);border-radius:0 0 var(--r-md) var(--r-md);z-index:var(--z-sticky)}
.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 var(--sp-6)}.form-grid .wide{grid-column:1/-1}.form-footer{display:flex;align-items:center;gap:var(--sp-4);flex-wrap:wrap;border-top:1px solid var(--c-line);padding-top:var(--sp-4)}.form-result{font-size:var(--fs-sm);color:var(--c-success)}.scope-note{font-size:var(--fs-xs);color:var(--c-muted);margin-bottom:var(--sp-6)}.modal-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--sp-4)}.modal-stage{padding:var(--sp-4);border-radius:var(--r-lg);background:var(--c-soft);min-width:0}.modal-stage>button{margin-bottom:var(--sp-3)}dialog.sample{position:relative;inset:auto;margin:0;padding:var(--sp-5);width:100%;max-width:none;box-shadow:var(--sh-2);border:1px solid var(--c-line);border-radius:var(--r-lg);background:var(--c-surface);color:var(--c-ink)}dialog.sample:modal{position:fixed;margin:auto;max-width:560px;width:calc(100% - 32px)}dialog.sample h3{font:var(--fs-xl) var(--f-display);margin-bottom:var(--sp-4)}dialog.sample .editor .ProseMirror{min-height:96px}.dialog-close{display:none}dialog:modal .dialog-close{display:inline-flex}.error-message{color:var(--c-danger);font-size:var(--fs-sm)}
.rules-grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--sp-6)}.reading-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:var(--sp-6)}.reading-item{min-width:0}.reading-item h3{font-size:var(--fs-sm);font-weight:600;margin-bottom:var(--sp-4)}.reading .ProseMirror{font-size:var(--fs-md)}.reading .ProseMirror input{pointer-events:none}.bubble{position:fixed;display:flex;padding:var(--sp-1);border:1px solid var(--c-line);border-radius:var(--r-md);background:var(--c-surface);box-shadow:var(--sh-pop);z-index:var(--z-dropdown);max-width:calc(100vw - 16px)}[hidden]{display:none!important}.link-dialog{max-width:480px}.link-dialog form{display:flex;flex-direction:column;gap:var(--sp-4)}.help{margin:var(--sp-4) 0;color:var(--c-muted);font-size:var(--fs-xs)}.quiet-tools>summary{cursor:pointer;font-size:var(--fs-xs);color:var(--c-muted);padding:var(--sp-2) var(--sp-4);min-height:36px;display:flex;align-items:center}.quiet-tools[open]>summary{border-bottom:1px solid var(--c-line)}.quiet-tools .format-bar{border-bottom:0;border-top:1px solid var(--c-line)}.bubble-access{font-size:var(--fs-xs);padding:var(--sp-1) var(--sp-2);border:0;background:transparent;color:var(--c-accent);cursor:pointer;min-height:32px}.field-actions{display:flex;align-items:center;gap:var(--sp-2)}.read-footer{margin-top:var(--sp-8);padding-top:var(--sp-5);border-top:1px solid var(--c-line);font-size:var(--fs-xs);color:var(--c-muted)}
.mode-b .concept{grid-template-columns:160px minmax(0,1fr);gap:var(--sp-10)}.mode-b .context{border:0;border-radius:0;background:transparent;padding:var(--sp-5) 0}.mode-b .chapter{border-top:1px solid var(--c-line);padding-top:var(--sp-6)}.mode-b .chapter:first-of-type{border-top:0}.mode-b .task-layout{grid-template-columns:minmax(0,1fr) 240px}.mode-b .task-aside{order:-1;border-left:0;border-right:1px solid var(--c-line);padding-left:0;padding-right:var(--sp-6);grid-column:1;width:240px}.mode-b .task-layout{grid-template-columns:240px minmax(0,1fr)}.mode-b .task-fields{grid-column:2;grid-row:1}.mode-b .edit-shell{border-color:transparent;border-radius:var(--r-sm);background:transparent;border-bottom-color:var(--c-line)}.mode-b .edit-shell:hover{background:var(--c-surface)}.mode-b .edit-shell:focus-within{background:var(--c-surface);border-color:var(--c-accent)}.mode-b .editor .ProseMirror{padding:var(--sp-3) var(--sp-2)}.mode-b .field-heading{margin-bottom:0}.mode-b .field-block{margin-bottom:var(--sp-6)}.mode-b .rationale{margin-top:var(--sp-2)}.mode-b .long .edit-shell,.mode-b .manuscript .edit-shell{background:var(--c-surface);border:1px solid var(--c-line);padding:var(--sp-5)}.mode-b .reading-grid{border-top:1px solid var(--c-line);padding-top:var(--sp-5)}
@media(max-width:1100px){.concept,.mode-b .concept{grid-template-columns:1fr}.index{position:static;flex-direction:row;flex-wrap:wrap;gap:var(--sp-1)}.index strong{display:none}.index a{padding:var(--sp-2) var(--sp-3);background:var(--c-soft)}.modal-grid{grid-template-columns:1fr}.modal-stage{display:grid;grid-template-columns:180px 1fr;gap:var(--sp-4);align-items:start}.rules-grid{grid-template-columns:1fr}}
@media(max-width:700px){.concept-header{padding:var(--sp-3) var(--sp-4);flex-wrap:wrap}.brand{gap:var(--sp-2)}.brand span{font-size:var(--fs-sm)}.concept,.mode-b .concept{padding:var(--sp-4);gap:var(--sp-5)}.index{flex-wrap:nowrap;overflow-x:auto;padding-bottom:var(--sp-1)}.index a{white-space:nowrap;min-height:44px;display:flex;align-items:center}.page-head h1{font-size:var(--fs-3xl)}.intro{font-size:var(--fs-sm)}.chapter-head{display:block}.chapter-head span{display:block;margin-top:var(--sp-1)}.context{padding:var(--sp-4)}.task-layout,.mode-b .task-layout{display:flex;flex-direction:column}.task-aside,.mode-b .task-aside{width:auto;border:0;border-top:1px solid var(--c-line);padding:var(--sp-4) 0 0;order:1}.task-aside dl{grid-template-columns:1fr 1fr}.task-aside .aside-note{display:none}.form-grid,.reading-grid{grid-template-columns:1fr}.modal-stage{display:block;padding:var(--sp-3)}dialog.sample{padding:var(--sp-4)}.format-bar button,.bubble button,.bubble-access,.quiet-tools>summary{min-height:44px;min-width:44px}.editor .ProseMirror{font-size:var(--fs-lg);padding:var(--sp-3)}.rationale{font-size:var(--fs-xs)}.field-heading{align-items:flex-start}.field-actions{flex-wrap:wrap;justify-content:flex-end}.field-heading .state{max-width:110px;text-align:right}.mode-b .long .edit-shell,.mode-b .manuscript .edit-shell{padding:var(--sp-3)}.format-bar{gap:0}.format-bar button{padding:var(--sp-2)}.chapter{margin-bottom:var(--sp-8)}.form-footer{gap:var(--sp-3)}.concept-header>a{min-height:44px;display:flex;align-items:center}}
'''

JS = r'''
import {Editor,extensions,setupMarkdown,preprocess,safeUrl} from '../../core/web/static/vendor/tiptap.bundle.js';
const data=__DATA__, editors=new Map();window.demoEditors=editors;window.demoReady=false;
const bubble=document.querySelector('.bubble');let active=null,linkEditor=null,composing=false;
const labels={bold:'굵게',italic:'기울임',link:'링크',task:'체크',bullet:'목록',heading:'제목',quote:'인용',code:'코드',table:'표',undo:'되돌리기'};
function buttons(keys){return keys.map(k=>`<button type="button" data-command="${k}" aria-label="${labels[k]}" title="${labels[k]}${k==='bold'?' · Ctrl+B':k==='italic'?' · Ctrl+I':k==='link'?' · Ctrl+K':''}" aria-pressed="false">${k==='bold'?'<b>가</b>':k==='italic'?'<i>가</i>':labels[k]}</button>`).join('')}
document.querySelectorAll('[data-tools]').forEach(x=>x.innerHTML=buttons(x.dataset.tools.split(',')));
bubble.innerHTML=buttons(['bold','italic','link']);
function sync(id,ed){const host=document.querySelector(`[data-field="${id}"]`);if(!host)return;host.querySelector('[name]').value=ed.getMarkdown();host.querySelector('.state').textContent='수정 중';const v=document.querySelector(`[data-mirror="${id}"]`);if(v&&v._editor)v._editor.commands.setContent(ed.getJSON());}
function save(id,ed){if(ed.view.composing||composing)return;const host=document.querySelector(`[data-field="${id}"]`);if(!host||!host.hasAttribute('data-autosave'))return;host.querySelector('[name]').value=ed.getMarkdown();host.querySelector('[name]').dispatchEvent(new Event('change',{bubbles:true}));host.querySelector('.state').textContent='이 화면에 반영됨';}
for(const item of data){const host=document.querySelector(`[data-field="${item.id}"]`);const ed=new Editor({element:host.querySelector('.editor'),extensions:extensions({placeholder:item.placeholder||'여기에 내용을 씁니다.'}),content:preprocess(item.text),contentType:'markdown',editorProps:{attributes:{role:'textbox','aria-multiline':'true','aria-labelledby':item.id+'-label','aria-describedby':item.id+'-help','aria-required':String(!!item.required)}},onUpdate:({editor})=>sync(item.id,editor),onSelectionUpdate:({editor})=>{active=editor;updateBubble()},onFocus:({editor})=>{active=editor},onBlur:({editor})=>{save(item.id,editor);setTimeout(()=>{if(!bubble.contains(document.activeElement))bubble.hidden=true},150)},onTransaction:({editor})=>{host.querySelectorAll('[data-command]').forEach(b=>b.setAttribute('aria-pressed',String(editor.isActive({bold:'bold',italic:'italic',link:'link',task:'taskList',bullet:'bulletList',heading:'heading',quote:'blockquote',code:'codeBlock',table:'table'}[b.dataset.command]||'nonexistent'))))}});setupMarkdown(ed);editors.set(item.id,ed);host.querySelector('[name]').value=ed.getMarkdown();ed.view.dom.addEventListener('compositionstart',()=>{composing=true;bubble.hidden=true});ed.view.dom.addEventListener('compositionend',()=>{composing=false});ed.view.dom.addEventListener('keydown',e=>{if(e.isComposing||ed.view.composing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openLink(ed)}});host.querySelector('[data-open-tools]')?.addEventListener('click',()=>{active=ed;showBubble(host.querySelector('[data-open-tools]').getBoundingClientRect());bubble.querySelector('button').focus({preventScroll:true})});}
document.querySelectorAll('[data-mirror]').forEach(el=>{el._editor=new Editor({element:el,editable:false,extensions:extensions(),content:editors.get(el.dataset.mirror).getJSON()});el._editor.view.dom.setAttribute('aria-label',el.dataset.readlabel||'읽기 전용 본문')});
function showBubble(rect){bubble.hidden=false;const w=bubble.getBoundingClientRect().width;const h=bubble.getBoundingClientRect().height;const vp=window.visualViewport;const left=vp?.offsetLeft||0;const top=vp?.offsetTop||0;const width=vp?.width||innerWidth;const height=vp?.height||innerHeight;bubble.style.left=Math.max(left+8,Math.min(rect.left,left+width-w-8))+'px';bubble.style.top=Math.max(top+8,Math.min(rect.top-h-8,top+height-h-8))+'px';}
function updateBubble(){if(bubble.contains(document.activeElement))return;if(!active||active.view.composing||composing||active.state.selection.empty){bubble.hidden=true;return}const host=active.view.dom.closest('[data-field]');if(host.dataset.mode==='passive'){bubble.hidden=true;return}const r=getSelection()?.rangeCount?getSelection().getRangeAt(0).getBoundingClientRect():null;if(r&&r.width)showBubble(r)}
document.addEventListener('selectionchange',()=>requestAnimationFrame(updateBubble));document.addEventListener('scroll',()=>bubble.hidden=true,true);window.addEventListener('resize',()=>bubble.hidden=true);document.addEventListener('keydown',e=>{if(e.key==='Escape'){bubble.hidden=true;active?.commands.focus()}});
function openLink(ed){linkEditor=ed;bubble.hidden=true;const d=document.querySelector('#link-dialog');d.querySelector('input').value=ed.getAttributes('link').href||'';d.querySelector('.error-message').textContent='';d.showModal();d.querySelector('input').focus()}
function command(ed,k){if(!ed||ed.view.composing)return;if(k==='link'){openLink(ed);return}const c=ed.chain().focus();({bold:()=>c.toggleBold().run(),italic:()=>c.toggleItalic().run(),task:()=>c.toggleTaskList().run(),bullet:()=>c.toggleBulletList().run(),heading:()=>c.toggleHeading({level:2}).run(),quote:()=>c.toggleBlockquote().run(),code:()=>c.toggleCodeBlock().run(),table:()=>c.insertTable({rows:3,cols:3,withHeaderRow:true}).run(),undo:()=>c.undo().run()})[k]?.()}
document.addEventListener('pointerdown',e=>{if(e.target.closest('[data-command]'))e.preventDefault()});document.addEventListener('click',e=>{const b=e.target.closest('[data-command]');if(b)command(editors.get(b.closest('[data-field]')?.dataset.field)||active,b.dataset.command)});
document.querySelector('#link-dialog form').addEventListener('submit',e=>{e.preventDefault();const d=e.currentTarget.closest('dialog'),url=d.querySelector('input').value.trim();if(url&&!safeUrl(url)){d.querySelector('.error-message').textContent='⚠ https:// 또는 사이트 안의 경로를 입력하세요.';return}d.close();url?linkEditor.chain().focus().extendMarkRange('link').setLink({href:url}).run():linkEditor.chain().focus().unsetLink().run()});
document.querySelector('[data-close-link]').onclick=()=>{document.querySelector('#link-dialog').close();linkEditor?.commands.focus()};
document.querySelectorAll('form.demo-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();let bad=false;form.querySelectorAll('[data-field]').forEach(host=>{const ed=editors.get(host.dataset.field);if(ed.view.composing){bad=true;return}const error=host.querySelector('.error-message');if(host.dataset.required==='true'&&!ed.getText().trim()){error.textContent='⚠ 사유를 입력하세요.';ed.view.dom.setAttribute('aria-invalid','true');ed.commands.focus();bad=true}else{error.textContent='';ed.view.dom.removeAttribute('aria-invalid');host.querySelector('[name]').value=ed.getMarkdown();host.querySelector('.state').textContent='이 화면에 반영됨'}});if(!bad)form.querySelector('.form-result').textContent='내용을 반영했습니다. · 시안'}));
document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>{const d=document.getElementById(b.dataset.modal);d.removeAttribute('open');d.showModal()});document.querySelectorAll('dialog.sample').forEach(d=>{d.addEventListener('close',()=>d.setAttribute('open',''));d.querySelector('.dialog-close').onclick=()=>d.close()});window.demoReady=true;
'''

def build(mode):
    is_a=mode=='a'; data=[]
    def field(id,label,text,kind='short',typ='bubble',reason='',auto=False,required=False,wide=False):
        data.append(dict(id=id,text=text,required=required))
        tools={'compact':'bold,task,link','full':'heading,bold,italic,link,bullet,task,quote,code,table,undo'}
        bar=''
        if typ in tools:
            bar=f'<div class="format-bar {"bottom" if id=="document" else ""}" role="group" aria-label="{label} 서식" data-tools="{tools[typ]}"></div>'
        elif typ=='bubble' and kind in ['long','manuscript']:
            bar=f'<details class="quiet-tools"><summary>문서 도구 펼치기</summary><div class="format-bar" role="group" aria-label="{label} 문서 도구" data-tools="heading,bullet,task,quote,code,table,undo"></div></details>'
        name={'compact':'축약','full':'전체','bubble':'말풍선','passive':'패시브만'}[typ]
        access='<button class="bubble-access" type="button" data-open-tools aria-label="'+label+' 서식 메뉴">서식</button>' if typ=='bubble' else ''
        editor='<div class="editor md"></div>'
        content=editor+bar if id=='document' or typ=='bubble' else bar+editor
        return f'''<div class="field-block {kind} {'wide' if wide else ''}" data-field="{id}" data-mode="{typ}" data-required="{str(required).lower()}" {'data-autosave' if auto else ''}>
        <div class="field-heading"><span class="field-label" id="{id}-label">{label}{' <span class="muted">· 필수</span>' if required else ''}</span><span class="field-actions">{access}<span class="state" aria-live="polite">{'변경 시 자동 반영' if auto else '작성 중'}</span></span></div>
        <div class="edit-shell">{content}</div><input type="hidden" name="{id}"><p class="rationale" id="{id}-help"><b>{name}</b> · {reason}</p><p class="error-message" role="alert"></p></div>'''
    def footer(label):return f'<div class="form-footer"><button class="btn" type="submit">{label}</button><span class="form-result" role="status"></span></div>'
    task=''.join([
      field('description','설명','새로 합류한 팀원이 첫날에 길을 잃지 않도록, **시작 안내**를 정리합니다.\n\n[현재 안내 문서](/guide)를 읽고 빠진 내용을 보태 주세요.','medium','compact' if is_a else 'bubble','체크·링크를 가까이 두고 문서 도구는 덜어냅니다.' if is_a else '문장을 선택했을 때만 서식을 고릅니다.',True),
      field('acceptance','완료 조건','- [x] 계정 만들기 안내\n- [ ] 첫 태스크까지 따라 해 보기\n- [ ] 모바일에서 링크 확인','medium','compact' if is_a else 'bubble','체크리스트를 가장 빠르게 추가합니다.' if is_a else '줄 앞에 [ ] 를 쓰면 바로 체크리스트가 됩니다.',True),
      field('progress','진행 메모','10/9 · 안내 문서 초안을 공유했습니다.\n\n다음은 **모바일 화면 확인**입니다.','short','bubble' if is_a else 'passive','선택한 문장만 강조하고 나머지 공간은 기록에 씁니다.' if is_a else '짧게 이어 쓰는 기록은 버튼 없이, 단축키로 강조합니다.',True)])
    decision=''.join(field(id,label,text,'short','bubble','네 칸에 툴바를 반복하지 않고 선택한 문장에만 도구를 띄웁니다.',wide=(id=='summary')) for id,label,text in [('summary','요약','시작 안내는 역할별로 나누지 않고 **하나의 문서**로 관리합니다.'),('reason','이유','처음 온 팀원이 같은 순서로 따라갈 수 있습니다.'),('impact','영향','기존 안내 링크를 새 문서로 연결합니다.'),('alternatives','검토한 대안','- 역할마다 별도 안내\n- 첫 화면에서 직접 설명')])
    modals=''
    for id,title,button in [('pause','멈춤 사유','잠시 멈추기'),('blocked','막힘 사유','막힘으로 변경'),('reject','반려 사유','반려하기')]:
        modals+=f'<div class="modal-stage"><button type="button" class="btn sm" data-modal="modal-{id}">{title} 모달 열기</button><dialog open class="sample" id="modal-{id}" aria-labelledby="modal-title-{id}"><form class="demo-form"><h3 id="modal-title-{id}">{button}</h3>'+field(id,'사유','',typ='passive',reason='1~3줄의 이유에 집중합니다. 링크 붙여넣기·단축키는 그대로.',required=True)+footer(button)+'<button type="button" class="btn dialog-close">닫기</button></form></dialog></div>'
    request=field('request','요청 내용','## 필요한 것\n팀 시작 안내에 들어갈 화면 캡처를 부탁드립니다.\n\n- [ ] 데스크톱 첫 화면\n- [ ] 모바일 태스크 패널\n\n가능하면 **다음 주 월요일**까지 부탁드립니다.','long','compact' if is_a else 'bubble','요청에 필요한 강조·체크·링크만 남깁니다.' if is_a else '요청을 편지처럼 씁니다. 구조 도구는 필요할 때 펼칩니다.')
    rules=''
    for id,label,text in [('projectrules','프로젝트 추가 규칙','## 검토를 요청하기 전에\n- [ ] 완료 조건을 모두 확인합니다.\n- [ ] 변경 내용을 문서에 남깁니다.\n\n막힌 일이 생기면 **당일에 공유**합니다.'),('orgrules','조직 거버넌스','## 우리가 일하는 방법\n결정에는 이유를 함께 남깁니다.\n\n### 기록과 공유\n- 결정 기록은 팀 모두에게 공개합니다.\n- 중요한 변경은 검토 후 반영합니다.\n\n> 서로의 다음 걸음이 보이도록 씁니다.')]:
        rules+='<form class="demo-form">'+field(id,label,text,'long','full' if is_a else 'bubble','규칙의 제목·목록·인용을 바로 정리합니다.' if is_a else '읽는 화면처럼 쓰고, 구조 편집이 필요할 때만 도구를 엽니다.')+footer('규칙 저장')+'</form>'
    portfolio=field('portfolio','초안 본문','## 첫날부터 함께 일할 수 있도록\n\n팀원이 늘어날수록 같은 설명을 반복하는 일이 많아졌습니다. 우리는 안내를 더 많이 만드는 대신, **처음부터 끝까지 따라갈 수 있는 흐름**을 만들었습니다.\n\n### 우리가 발견한 문제\n처음 온 사람에게는 짧은 링크 하나도 어디로 가는지 알 수 없는 문이었습니다. 계정을 만들고, 팀을 찾고, 첫 태스크를 열기까지의 경험을 함께 살폈습니다.\n\n### 바꾼 것\n1. 시작 안내를 하나로 모았습니다.\n2. 각 단계에 실제 화면과 다음 행동을 적었습니다.\n3. 모바일에서도 혼자 따라 할 수 있는지 확인했습니다.\n\n> 좋은 안내는 설명을 끝내는 것이 아니라, 다음 행동을 시작하게 합니다.\n\n### 다음 실험\n첫 주를 마친 팀원의 이야기를 듣고, 아직 막히는 곳을 다시 고칩니다.','manuscript','full' if is_a else 'bubble','긴 글의 구조를 다듬는 전체 도구를 제공합니다.' if is_a else '초안은 긴 호흡으로 씁니다. 말풍선과 펼침 도구만 남깁니다.')
    doc=field('document','문서·회의록 본문','## 10월 9일 · 시작 안내 점검\n\n**참석** 지윤, 민수, 서연\n\n### 오늘 나눈 이야기\n처음 태스크를 받았을 때 무엇을 먼저 확인해야 하는지 이야기했습니다. 설명과 완료 조건이 한눈에 보이면 좋겠다는 의견이 있었습니다.\n\n### 결정한 것\n- 안내 문서는 하나로 유지합니다.\n- 완료 조건은 체크리스트로 씁니다.\n\n### 다음 할 일\n- [x] 안내 문서 초안 공유\n- [ ] 실제 화면 캡처 추가\n- [ ] 새 팀원과 따라 해 보기\n\n[시작 안내](/guide)를 보며 이어서 논의합니다.','long','full' if is_a else 'bubble','기존 하단 고정 툴바를 유지해 긴 글 끝에서도 도구에 닿습니다.' if is_a else '문서도 같은 쓰기 방식입니다. 긴 글에서만 구조 도구를 펼칩니다.',True)
    title='쓰는 일에 맞춘 도구' if is_a else '글을 쓰면, 도구가 따라옵니다'
    intro='자주 쓰는 체크와 링크는 가까이. 짧은 이유는 가볍게. 긴 문서는 차근차근 구조를 잡습니다.' if is_a else '입력칸보다 한 장의 기록에 가깝게. 문장을 선택하면 작은 도구가 나타나고, 나머지 시간에는 글만 남습니다.'
    html=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>유달리 · Astra {mode.upper()} · {title}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Jua&display=swap"><link rel="stylesheet" href="../../core/web/static/app.css"><style>{CSS}</style></head><body class="mode-{mode}">
    <a class="skip-link" href="#main-content">본문으로 건너뛰기</a><header class="concept-header"><div class="brand"><img src="../../core/web/static/brand/udally.svg" alt="유달리"><span>작은 팀의 작업실</span></div><a href="astra-{'b' if is_a else 'a'}.html">{'B · 글 중심 시안' if is_a else 'A · 맥락별 도구 시안'} 보기 →</a></header>
    <div class="concept"><nav class="index" aria-label="입력 화면 목차"><strong>ASTRA {mode.upper()} · 편집기 시안</strong><a href="#task">태스크</a><a href="#decision">결정 기록</a><a href="#stop">사유 입력</a><a href="#request">요청</a><a href="#rules">거버넌스</a><a href="#portfolio">포트폴리오</a><a href="#document-section">문서·회의록</a><a href="#read">읽기 화면</a></nav>
    <main class="canvas" id="main-content"><div class="page-head"><h1>{title}</h1><p class="intro">{intro}</p></div><p class="scope-note">직접 써 보는 시안 · 변경 내용은 현재 화면에만 반영됩니다. 새로고침하면 처음으로 돌아갑니다.</p>
    <section class="chapter" id="task"><div class="chapter-head"><h2>01 · 일의 맥락을 함께 씁니다</h2><span>태스크 상세 패널 · 변경 후 포커스를 옮기면 반영</span></div><div class="context"><div class="context-path">팀 시작 안내 / TASK-128</div><div class="context-head"><h3>새 팀원을 위한 시작 안내 정리</h3><span class="pill static doing">● 진행 중</span></div><div class="task-layout"><div class="task-fields">{task}</div><aside class="task-aside"><dl><div><dt>담당</dt><dd>김지윤</dd></div><div><dt>목표일</dt><dd>10월 12일</dd></div><div><dt>프로젝트</dt><dd>팀 시작 안내</dd></div><div><dt>다음 단계</dt><dd>팀원 검토</dd></div></dl><div class="aside-note"><b>{'체크와 링크를 가장 가까이' if is_a else '서식보다 먼저 보이는 내용'}</b><p>{'설명·완료 조건에는 축약 도구를, 메모에는 선택 말풍선을 둡니다.' if is_a else '늘 보이는 도구 막대를 비웠습니다. 글을 선택하거나 서식 버튼으로 필요한 도구만 꺼냅니다.'}</p><p>Ctrl+B 굵게<br>Ctrl+I 기울임<br>Ctrl+K 링크</p></div></aside></div></div></section>
    <section class="chapter" id="decision"><div class="chapter-head"><h2>02 · 결정은 이유와 함께</h2><span>여러 칸이 하나의 기록</span></div><form class="context demo-form"><div class="context-head"><h3>결정 기록 추가</h3><span class="badge">사용자 입력</span></div><div class="form-grid">{decision}</div>{footer('결정 기록 저장')}</form></section>
    <section class="chapter" id="stop"><div class="chapter-head"><h2>03 · 잠깐 멈추는 이유</h2><span>패시브만 · 필수 검증 · 실제 모달로 열기 가능</span></div><div class="modal-grid">{modals}</div></section>
    <section class="chapter" id="request"><div class="chapter-head"><h2>04 · 필요한 일을 부탁합니다</h2><span>요청 만들기 · 제출형</span></div><form class="context demo-form"><div class="context-head"><h3>새 요청</h3><span class="muted t13">받는 사람 · 디자인 팀</span></div><label class="field">제목<input class="input" value="시작 안내 화면 캡처 요청"></label><div class="help">상황과 필요한 결과를 함께 적어 주세요.</div>{request}{footer('요청 보내기')}</form></section>
    <section class="chapter" id="rules"><div class="chapter-head"><h2>05 · 함께 지킬 약속</h2><span>조직·프로젝트 설정 · 관리자 전용</span></div><div class="context"><div class="context-head"><h3>거버넌스</h3><span class="badge">관리자</span></div><div class="rules-grid">{rules}</div></div></section>
    <section class="chapter" id="portfolio"><div class="chapter-head"><h2>06 · 일을 한 편의 이야기로</h2><span>포트폴리오 초안 · 긴 글 작성</span></div><form class="context demo-form"><div class="context-path">포트폴리오 / 팀 시작 안내</div><div class="context-head"><h3>시작을 쉽게 만든 기록</h3><span class="badge">초안</span></div>{portfolio}{footer('초안 저장')}</form></section>
    <section class="chapter" id="document-section"><div class="chapter-head"><h2>07 · 논의에서 다음 걸음까지</h2><span>문서·회의록 · 같은 마크다운 형식</span></div><div class="context"><div class="context-path">문서 / 주간 회의</div>{doc}</div></section>
    <section class="chapter" id="read"><div class="chapter-head"><h2>08 · 쓰던 모습 그대로 읽습니다</h2><span>동일한 Tiptap 렌더 · 위 입력과 실시간 연결</span></div><div class="context reading-grid"><div class="reading-item"><h3>태스크 설명 보기</h3><div class="reading md" data-mirror="description" data-readlabel="태스크 설명 읽기 전용"></div></div><div class="reading-item"><h3>결정 기록 보기</h3><div class="reading md" data-mirror="summary" data-readlabel="결정 기록 읽기 전용"></div></div><div class="reading-item"><h3>요청·이슈 본문 보기</h3><div class="reading md" data-mirror="request" data-readlabel="요청 본문 읽기 전용"></div></div></div></section>
    <details class="help"><summary>입력 방법 보기</summary><p>줄 처음에 # + 공백은 제목, - + 공백은 목록, [ ] + 공백은 체크리스트입니다. 백틱 세 개 다음 공백은 코드 블록입니다. Ctrl+B / I / K로 서식을 넣거나 URL을 붙여 넣어 링크를 만들 수 있습니다. 모바일에서는 글을 길게 눌러 선택합니다.</p></details><footer class="read-footer">유달리 · 모여서, 한 걸음 / Astra {mode.upper()} · {'맥락에 따라 달라지는 도구 밀도' if is_a else '패시브 입력과 선택 말풍선'}<br>시안의 저장·제출은 서버 요청 없이 마크다운 필드와 읽기 화면만 갱신합니다.</footer></main></div>
    <div class="bubble" role="group" aria-label="선택한 글 서식" hidden></div><dialog class="link-dialog" id="link-dialog" aria-labelledby="link-title"><form><h2 id="link-title">링크 넣기</h2><label class="field">주소<input class="input" type="text" placeholder="https://" aria-describedby="link-help"></label><p class="muted t13" id="link-help">주소를 비우고 적용하면 링크를 지웁니다.</p><p class="error-message" role="alert"></p><div class="row"><button class="btn primary">적용</button><button type="button" class="btn" data-close-link>취소</button></div></form></dialog>
    <script type="module">{JS.replace('__DATA__',json.dumps(data,ensure_ascii=False))}</script></body></html>'''
    (OUT/f'astra-{mode}.html').write_text(html,encoding='utf-8')

if __name__=='__main__':
    build('a');build('b')
