# Generated by Django 5.2.17 on 2026-09-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_discord_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="governance_extra",
            field=models.TextField(blank=True, verbose_name="프로젝트 거버넌스"),
        ),
        migrations.AddField(
            model_name="project",
            name="settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="설정"),
        ),
    ]
