# Generated by Django 5.2.17 on 2026-10-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_settings_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="discord_channel_managed",
            field=models.BooleanField(default=False, verbose_name="채널 자동 관리"),
        ),
    ]
