# Generated by Django 5.2.17 on 2026-10-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_discord_channel_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("org", "조직 전체"), ("teams", "담당 팀만")],
                default="org",
                max_length=5,
                verbose_name="공개 범위",
            ),
        ),
    ]
