# Generated by Django 5.2.17 on 2026-10-05 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_project_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="gh_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gh_number__isnull", False)),
                fields=("project", "gh_number"),
                name="milestone_project_gh_number",
            ),
        ),
    ]
