# Generated by Django 5.2.17 on 2026-10-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0009_team_dev_tools_is_private"),
        ("projects", "0012_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doc",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="docs",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="doc",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="docs",
                to="orgs.team",
            ),
        ),
    ]
