# Generated by Django 5.2.17 on 2026-10-07 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# 감사 기록은 append-only다. QuerySet.update()·delete()와 raw SQL까지 DB가 막는다(IMPL-PLAN-10 §4.2).
POSTGRES_UP = [
    """CREATE OR REPLACE FUNCTION ops_audit_block() RETURNS trigger AS $$
    BEGIN RAISE EXCEPTION 'ops_opsauditlog is append-only'; END $$ LANGUAGE plpgsql""",
    """CREATE TRIGGER ops_audit_no_update BEFORE UPDATE OR DELETE ON ops_opsauditlog
    FOR EACH ROW EXECUTE FUNCTION ops_audit_block()""",
]
POSTGRES_DOWN = [
    "DROP TRIGGER IF EXISTS ops_audit_no_update ON ops_opsauditlog",
    "DROP FUNCTION IF EXISTS ops_audit_block()",
]
SQLITE_UP = [
    """CREATE TRIGGER ops_audit_no_update BEFORE UPDATE ON ops_opsauditlog
    BEGIN SELECT RAISE(ABORT, 'ops_opsauditlog is append-only'); END""",
    """CREATE TRIGGER ops_audit_no_delete BEFORE DELETE ON ops_opsauditlog
    BEGIN SELECT RAISE(ABORT, 'ops_opsauditlog is append-only'); END""",
]
SQLITE_DOWN = [
    "DROP TRIGGER IF EXISTS ops_audit_no_update",
    "DROP TRIGGER IF EXISTS ops_audit_no_delete",
]
SQL = {"postgresql": (POSTGRES_UP, POSTGRES_DOWN), "sqlite": (SQLITE_UP, SQLITE_DOWN)}


def _run(schema_editor, index):
    stmts = SQL.get(schema_editor.connection.vendor)
    if stmts is None:
        raise RuntimeError("감사 기록 트리거가 없는 DB입니다(postgresql·sqlite만 지원).")
    for sql in stmts[index]:
        schema_editor.execute(sql)


def add_triggers(apps, schema_editor):
    _run(schema_editor, 0)


def drop_triggers(apps, schema_editor):
    _run(schema_editor, 1)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor_username", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user.suspend", "사용자 정지"),
                            ("user.reactivate", "사용자 재활성"),
                            ("user.reset_link", "비밀번호 재설정 링크 발급"),
                            ("user.unlock", "로그인 잠금 해제"),
                            ("user.grant_staff", "운영자 권한 부여"),
                            ("user.revoke_staff", "운영자 권한 회수"),
                            ("token.revoke", "토큰 폐기"),
                            ("export.json", "운영 데이터 내보내기"),
                            ("audit.export", "감사 기록 내보내기"),
                            ("admin.access", "Django 관리 화면 접근"),
                            ("backup.record", "백업 결과 기록"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=20)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("target_label", models.CharField(blank=True, max_length=200)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("ip", models.CharField(blank=True, max_length=45)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["created_at"], name="ops_opsaudi_created_394fdd_idx"),
                    models.Index(fields=["action"], name="ops_opsaudi_action_3bc23e_idx"),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="ops_opsaudi_target__6a070e_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(add_triggers, drop_triggers),
    ]
