# Generated by Django 5.2.17 on 2026-09-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="target_type",
            field=models.CharField(
                choices=[("task", "task"), ("project", "project"), ("org", "org")],
                max_length=10,
            ),
        ),
    ]
