# Generated by Django 5.2.17 on 2026-09-23 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_settings_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDecisionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user_input", "사용자 입력"),
                            ("ai_judgment", "AI 작업 판단"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("major_choice", "주요 선택"),
                            ("requirement", "요구·제약"),
                            ("answer", "명시적 답변"),
                            ("steer", "방향 수정"),
                            ("implementation_instruction", "구현 방식 지시"),
                            ("ai_workflow_instruction", "AI 협업 방식 지시"),
                        ],
                        max_length=26,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("captured", "세션에서 수집"),
                            ("proposed", "확인 대기"),
                            ("confirmed", "사용자 확인"),
                            ("rejected", "제외"),
                            ("recorded", "기록됨"),
                            ("superseded", "대체됨"),
                        ],
                        max_length=10,
                    ),
                ),
                ("question_summary", models.CharField(blank=True, max_length=300)),
                ("summary", models.CharField(max_length=800)),
                ("reason_summary", models.CharField(blank=True, max_length=500)),
                ("rejection_reason", models.CharField(blank=True, max_length=300)),
                ("alternatives", models.JSONField(blank=True, default=list)),
                ("impact_summary", models.CharField(blank=True, max_length=500)),
                (
                    "evidence_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("explicit_reply", "명시적 답변"),
                            ("explicit_instruction", "명시적 지시"),
                            ("inferred", "AI 추론"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "웹"), ("api", "API"), ("mcp", "MCP")],
                        max_length=3,
                    ),
                ),
                ("client_name", models.CharField(blank=True, max_length=80)),
                ("session_ref", models.CharField(blank=True, max_length=200)),
                ("verbatim_text", models.CharField(blank=True, max_length=4000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("source_time", models.DateTimeField(blank=True, null=True)),
                ("client_request_id", models.UUIDField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_task_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_task_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_task_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseding_records",
                        to="tasks.taskdecisionrecord",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_records",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["task", "created_at", "id"],
                        name="tasks_taskd_task_id_3e07c8_idx",
                    ),
                    models.Index(
                        fields=["task", "status", "created_at"],
                        name="tasks_taskd_task_id_08fee7_idx",
                    ),
                    models.Index(
                        fields=["confirmed_by", "confirmed_at"],
                        name="tasks_taskd_confirm_04a594_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("summary", ""), _negated=True),
                        name="decision_summary_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "input_type__in",
                                    [
                                        "major_choice",
                                        "requirement",
                                        "answer",
                                        "steer",
                                        "implementation_instruction",
                                        "ai_workflow_instruction",
                                    ],
                                ),
                                ("kind", "user_input"),
                            ),
                            models.Q(
                                ("input_type__isnull", True), ("kind", "ai_judgment")
                            ),
                            _connector="OR",
                        ),
                        name="decision_kind_input_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "evidence_basis__in",
                                    [
                                        "explicit_reply",
                                        "explicit_instruction",
                                        "inferred",
                                    ],
                                ),
                                ("kind", "user_input"),
                                (
                                    "status__in",
                                    [
                                        "captured",
                                        "proposed",
                                        "confirmed",
                                        "rejected",
                                        "superseded",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("evidence_basis__isnull", True),
                                ("kind", "ai_judgment"),
                                ("status__in", ["recorded", "superseded"]),
                            ),
                            _connector="OR",
                        ),
                        name="decision_kind_status_basis",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("confirmed_at__isnull", False),
                                ("confirmed_by__isnull", False),
                                ("kind", "user_input"),
                                ("status", "confirmed"),
                            ),
                            models.Q(
                                ("confirmed_at__isnull", True),
                                ("confirmed_by__isnull", True),
                                ("kind", "user_input"),
                                ("status__in", ["captured", "proposed", "rejected"]),
                            ),
                            models.Q(
                                ("confirmed_at__isnull", True),
                                ("confirmed_by__isnull", True),
                                ("kind", "user_input"),
                                ("status", "superseded"),
                            ),
                            models.Q(
                                ("confirmed_at__isnull", False),
                                ("confirmed_by__isnull", False),
                                ("kind", "user_input"),
                                ("status", "superseded"),
                            ),
                            models.Q(
                                ("confirmed_at__isnull", True),
                                ("confirmed_by__isnull", True),
                                ("kind", "ai_judgment"),
                            ),
                            _connector="OR",
                        ),
                        name="decision_confirmation_fields",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("client_request_id__isnull", False),
                            ("subject_user__isnull", False),
                        ),
                        fields=("task", "subject_user", "client_request_id"),
                        name="decision_req_user_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("client_request_id__isnull", False),
                            ("subject_user__isnull", True),
                        ),
                        fields=("task", "client_request_id"),
                        name="decision_req_task_uniq",
                    ),
                ],
            },
        ),
    ]
