# Generated by Django 5.2.17 on 2026-10-04 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0006_teammembership_is_lead"),
        ("tasks", "0003_taskdecisionrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(blank=True, max_length=32)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["sent_at"], name="tasks_notic_sent_at_9f00bc_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("work", "작업 요청"),
                            ("assign", "담당 요청"),
                            ("general", "일반 요청"),
                        ],
                        max_length=7,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("body", models.TextField(blank=True, verbose_name="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("accepted", "수락"),
                            ("declined", "거절"),
                            ("cancelled", "취소"),
                            ("done", "완료"),
                        ],
                        default="pending",
                        max_length=9,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_note",
                    models.CharField(blank=True, max_length=300, verbose_name="답변"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "웹"),
                            ("api", "API"),
                            ("mcp", "AI"),
                            ("dc", "Discord"),
                            ("gh", "GitHub"),
                        ],
                        default="web",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="orgs.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="tasks.task",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="orgs.team",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "to_user"],
                        name="tasks_workr_status_6fccba_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("team__isnull", True),
                            ("to_user__isnull", True),
                            _connector="XOR",
                        ),
                        name="workrequest_one_target",
                    )
                ],
            },
        ),
    ]
