# Generated by Django 5.2.17 on 2026-10-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_notice_workrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="kind",
            field=models.CharField(
                choices=[
                    ("doc", "문서"),
                    ("out", "산출물"),
                    ("issue", "이슈"),
                    ("dash", "대시보드"),
                    ("other", "기타"),
                    ("pr", "PR"),
                    ("repo", "저장소"),
                ],
                default="doc",
                max_length=5,
            ),
        ),
    ]
