# Generated by Django 5.2.17 on 2026-10-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_discord_channel_management"),
        ("tasks", "0005_link_kind_out"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_template",
            field=models.BooleanField(default=False, verbose_name="템플릿"),
        ),
        migrations.AddField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="tasks.task",
                verbose_name="원본",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewing_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="검토자",
            ),
        ),
        migrations.AddField(
            model_name="workrequest",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="희망 기한"),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_template", True), _negated=True),
                    ("status", "todo"),
                    _connector="OR",
                ),
                name="task_template_is_todo",
            ),
        ),
    ]
