# Generated by Django 5.2.17 on 2026-10-04 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tasks.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_discord_channel_management"),
        ("tasks", "0006_task_series_reviewer_request_due"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(max_length=200, upload_to=tasks.models.attachment_path),
                ),
                ("name", models.CharField(max_length=200, verbose_name="파일 이름")),
                ("size", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "파일"),
                            ("out", "산출물"),
                            ("proof", "증빙"),
                        ],
                        default="file",
                        max_length=5,
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="메모"),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.project",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_by",
                        to="tasks.attachment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("project__isnull", False), ("task__isnull", True)),
                            models.Q(("project__isnull", True), ("task__isnull", False)),
                            _connector="OR",
                        ),
                        name="attachment_exactly_one_target",
                    )
                ],
            },
        ),
    ]
