# Generated by Django 5.2.17 on 2026-10-04 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_project_visibility"),
        ("tasks", "0007_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("replaces__isnull", False)),
                fields=("replaces",),
                name="attachment_single_successor",
            ),
        ),
    ]
