# Generated by Django 5.2.17 on 2026-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_attachment_single_successor"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
