# Generated by Django 5.2.17 on 2026-10-07 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_milestone_gh_number"),
        ("tasks", "0009_task_status_since"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="git_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.project",
                verbose_name="연동 프로젝트",
            ),
        ),
        migrations.CreateModel(
            name="TaskProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("widened", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "승인 대기"), ("active", "연결됨")],
                        default="active",
                        max_length=7,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_links",
                        to="projects.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="extra_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_tasks",
                through="tasks.TaskProject",
                to="projects.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskproject",
            constraint=models.UniqueConstraint(
                fields=("task", "project"), name="taskproject_task_project"
            ),
        ),
    ]
