# Generated by Django 5.2.17 on 2026-10-07 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_doc"),
        ("tasks", "0010_taskproject_git_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attachment",
            name="attachment_exactly_one_target",
        ),
        migrations.AddField(
            model_name="attachment",
            name="doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="projects.doc",
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("project__isnull", False),
                        ("task__isnull", True),
                        ("doc__isnull", True),
                    ),
                    models.Q(
                        ("project__isnull", True),
                        ("task__isnull", False),
                        ("doc__isnull", True),
                    ),
                    models.Q(
                        ("project__isnull", True),
                        ("task__isnull", True),
                        ("doc__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="attachment_exactly_one_target",
            ),
        ),
    ]
