# Generated by Django 5.2.17 on 2026-10-07 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_doc_scope_restrict"),
        ("tasks", "0011_attachment_doc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="tasks.task",
                verbose_name="상위 태스크",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("group__isnull", True),
                    models.Q(("group", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="task_group_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_template", True), _negated=True),
                    ("group__isnull", True),
                    _connector="OR",
                ),
                name="task_template_no_group",
            ),
        ),
    ]
