# Generated by Django 5.2.17 on 2026-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliosource",
            name="pr_merged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="병합 시각 스냅샷"),
        ),
        migrations.AddField(
            model_name="portfoliosource",
            name="pr_url",
            field=models.CharField(blank=True, max_length=300, verbose_name="병합 PR 주소 스냅샷"),
        ),
    ]
