# Generated by Django 5.2.17 on 2026-10-05 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_meetingnote_tags_alter_meetingnote_created_on"),
        ("orgs", "0009_team_dev_tools_is_private"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingnote",
            name="attendees",
            field=models.ManyToManyField(blank=True, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="meetingnote",
            name="source",
            field=models.CharField(
                choices=[("web", "웹"), ("voice", "음성 회의")],
                default="web",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="meetingnote",
            name="status",
            field=models.CharField(
                choices=[("draft", "초안"), ("final", "확정")],
                default="final",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="meetingnote",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="orgs.team",
            ),
        ),
        migrations.CreateModel(
            name="VoiceRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.CharField(max_length=32)),
                ("voice_channel_id", models.CharField(max_length=32)),
                ("host_changes", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("command", "/회의종료"),
                            ("host_left", "진행자 퇴장"),
                            ("max_length", "최대 길이"),
                            ("empty", "모두 퇴장"),
                            ("restart", "봇 재시작"),
                            ("failed", "실패"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recording", "녹음 중"),
                            ("transcribing", "전사 중"),
                            ("draft", "초안"),
                            ("done", "확정"),
                            ("failed", "실패"),
                        ],
                        default="recording",
                        max_length=20,
                    ),
                ),
                ("participants", models.JSONField(blank=True, default=list)),
                ("transcript_md", models.TextField(blank=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("audio_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="notes.meetingnote",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
