from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import LoginForm
from .views import (
    auth,
    decisions,
    discord,
    docs,
    events,
    github,
    me,
    notes,
    oauth,
    ops,
    orgs,
    portfolio,
    projects,
    roadmap,
    search,
    settings,
    tasks,
    teams,
    today,
)

urlpatterns = [
    path("", auth.root, name="root"),
    path("healthz", ops.healthz, name="healthz"),
    path("events", events.events, name="events"),
    path(
        "login",
        auth_views.LoginView.as_view(
            template_name="auth/login.html",
            redirect_authenticated_user=True,
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    # ---- MCP 커넥터용 OAuth 2.1 (web/views/oauth.py 맨 위 설명) ----
    path(
        ".well-known/oauth-authorization-server",
        oauth.metadata,
        name="oauth_metadata",
    ),
    path("oauth/register", oauth.register, name="oauth_register"),
    path("oauth/authorize", oauth.authorize, name="oauth_authorize"),
    path("oauth/token", oauth.token, name="oauth_token"),
    path("signup", auth.signup, name="signup"),
    path("join/<str:token>", auth.join, name="join"),
    path("today", today.today, name="today"),
    path("today/quick", today.quick_add, name="today_quick"),
    path("today/add/<int:task_id>", today.add, name="today_add"),
    path("today/exclude/<int:task_id>", today.exclude, name="today_exclude"),
    path("today/restore", today.restore, name="today_restore"),
    path("today/move/<int:task_id>/<str:direction>", today.move, name="today_move"),
    path("today/settings", today.auto_pull, name="today_settings"),
    path("me", me.me, name="me"),
    path("portfolio", portfolio.portfolio, name="portfolio"),
    path("portfolio/prompt", portfolio.portfolio_prompt, name="portfolio_prompt"),
    path("portfolio/drafts", portfolio.portfolio_create, name="portfolio_create"),
    path("portfolio/drafts/<int:draft_id>/save", portfolio.portfolio_save, name="portfolio_save"),
    path("portfolio/drafts/<int:draft_id>/markdown", portfolio.portfolio_export, name="portfolio_export"),
    path("org", orgs.org_current, name="org"),
    path("orgs", orgs.org_list, name="org_list"),
    path("orgs/new", orgs.org_new, name="org_new"),
    path("orgs/<int:org_id>", orgs.org_detail, name="org_detail"),
    path("orgs/<int:org_id>/teams", orgs.org_teams, name="org_teams"),
    path("orgs/<int:org_id>/governance", orgs.org_governance, name="org_governance"),
    path("orgs/<int:org_id>/settings", orgs.org_settings, name="org_settings"),
    path("orgs/<int:org_id>/teams/new", teams.team_new, name="team_new"),
    path("orgs/<int:org_id>/invites", orgs.invite_create, name="invite_create"),
    path("orgs/invites/<int:invite_id>/revoke", orgs.invite_revoke, name="invite_revoke"),
    path("orgs/memberships/<int:membership_id>/role", orgs.member_role, name="member_role"),
    path("orgs/memberships/<int:membership_id>/remove", orgs.member_remove, name="member_remove"),
    path("orgs/memberships/<int:membership_id>/tags", orgs.member_tags, name="member_tags"),
    path("teams/<int:team_id>", teams.team_detail, name="team_detail"),
    path("teams/<int:team_id>/edit", teams.team_edit, name="team_edit"),
    path("teams/<int:team_id>/delete", teams.team_delete, name="team_delete"),
    path("teams/<int:team_id>/members", teams.team_member_add, name="team_member_add"),
    path(
        "teams/<int:team_id>/members/<int:user_id>/remove",
        teams.team_member_remove,
        name="team_member_remove",
    ),
    path("teams/<int:team_id>/github/link", teams.team_github_link, name="team_github_link"),
    path("teams/<int:team_id>/github/create", teams.team_github_create, name="team_github_create"),
    path("teams/<int:team_id>/github/unlink", teams.team_github_unlink, name="team_github_unlink"),
    path(
        "teams/<int:team_id>/github/reconcile",
        teams.team_github_reconcile,
        name="team_github_reconcile",
    ),
    path("projects", projects.project_index, name="project_index"),
    path("projects/new", projects.project_new, name="project_new"),
    path("projects/<int:project_id>", projects.project_detail, name="project_detail"),
    path("projects/<int:project_id>/edit", projects.project_edit, name="project_edit"),
    path("projects/<int:project_id>/settings", projects.project_settings, name="project_settings"),
    path("projects/<int:project_id>/docs", docs.project_docs, name="project_docs"),
    path("projects/<int:project_id>/docs/new", docs.doc_new, name="doc_new"),
    path("projects/<int:project_id>/docs/upload", docs.doc_upload, name="doc_upload"),
    path("docs/<int:doc_id>/save", docs.doc_save, name="doc_save"),
    path("docs/<int:doc_id>/delete", docs.doc_delete, name="doc_delete"),
    path("tasks/<int:task_id>/docs/link", docs.task_doc_link, name="task_doc_link"),
    path(
        "tasks/<int:task_id>/docs/<int:doc_id>/unlink",
        docs.task_doc_unlink,
        name="task_doc_unlink",
    ),
    path("projects/<int:project_id>/tasks", projects.task_create, name="project_task_create"),
    path("projects/<int:project_id>/archive", projects.project_archive, name="project_archive"),
    path("projects/<int:project_id>/restore", projects.project_restore, name="project_restore"),
    path("projects/<int:project_id>/delete", projects.project_delete, name="project_delete"),
    path("projects/<int:project_id>/links", projects.link_add, name="project_link_add"),
    path("projects/<int:project_id>/api", projects.project_api, name="project_api"),
    path("tasks/<int:task_id>", tasks.task_detail, name="task_detail"),
    path("tasks/<int:task_id>/delete", tasks.task_delete, name="task_delete"),
    path("tasks/<int:task_id>/panel", tasks.task_panel, name="task_panel"),
    path("tasks/<int:task_id>/decisions", decisions.task_decisions, name="task_decisions"),
    path("tasks/<int:task_id>/decisions/<int:record_id>/confirm", decisions.decision_confirm, name="decision_confirm"),
    path("tasks/<int:task_id>/decisions/<int:record_id>/reject", decisions.decision_reject, name="decision_reject"),
    path("tasks/<int:task_id>/decisions/<int:record_id>/supersede", decisions.decision_supersede, name="decision_supersede"),
    path("tasks/<int:task_id>/meta", tasks.task_meta, name="task_meta"),
    path("tasks/<int:task_id>/row", tasks.task_row, name="task_row"),
    path("tasks/<int:task_id>/status", tasks.task_status, name="task_status"),
    path("tasks/<int:task_id>/text/<str:field>", tasks.task_text, name="task_text"),
    path("tasks/<int:task_id>/priority", tasks.task_priority, name="task_priority"),
    path("tasks/<int:task_id>/extend", tasks.task_extend, name="task_extend"),
    path("tasks/<int:task_id>/stop-reason", tasks.task_stop_reason, name="task_stop_reason"),
    path("tasks/<int:task_id>/checklist", tasks.checklist_add, name="checklist_add"),
    path(
        "tasks/checklist/<int:item_id>/<str:action>",
        tasks.checklist_action,
        name="checklist_action",
    ),
    path("tasks/<int:task_id>/links", tasks.link_add, name="task_link_add"),
    path("tasks/links/<int:link_id>/delete", tasks.link_delete, name="link_delete"),
    path("search", search.search, name="search"),
    path("settings/profile", settings.profile, name="profile"),
    path("settings/preferences", settings.preferences, name="preferences"),
    path("settings/profile/discord", settings.discord_link, name="discord_link"),
    path("settings/profile/discord/unlink", settings.discord_unlink, name="discord_unlink"),
    path("settings/tokens", settings.tokens, name="tokens"),
    path("settings/tokens/<int:token_id>/revoke", settings.token_revoke, name="token_revoke"),
    path("ops", ops.ops, name="ops"),
    path("ops/export.json", ops.export_json, name="export_json"),
    # ---- V2-04: 부하 현황 · 로드맵 (아래는 이 단계에서 추가) ----
    path("orgs/<int:org_id>/capacity", roadmap.capacity, name="org_capacity"),
    path("orgs/<int:org_id>/roadmap", roadmap.roadmap, name="org_roadmap"),
    path("orgs/<int:org_id>/milestones/new", roadmap.milestone_new, name="milestone_new"),
    path("milestones/<int:milestone_id>/edit", roadmap.milestone_edit, name="milestone_edit"),
    path(
        "milestones/<int:milestone_id>/delete",
        roadmap.milestone_delete,
        name="milestone_delete",
    ),
    path("orgs/<int:org_id>/dependencies", roadmap.dependency_add, name="dependency_add"),
    path(
        "dependencies/<int:dependency_id>/delete",
        roadmap.dependency_delete,
        name="dependency_delete",
    ),
    # ---- V2-05: 회의록 (아래는 이 단계에서 추가) ----
    path("orgs/<int:org_id>/notes", notes.org_notes, name="org_notes"),
    path("orgs/<int:org_id>/notes/new", notes.note_new, name="note_new"),
    path("orgs/<int:org_id>/notes/upload", notes.note_upload, name="note_upload"),
    path("notes/<int:note_id>/save", notes.note_save, name="note_save"),
    path("notes/<int:note_id>/delete", notes.note_delete, name="note_delete"),
    path("tasks/<int:task_id>/notes", notes.task_note_link, name="task_note_link"),
    path(
        "tasks/<int:task_id>/notes/<int:note_id>/unlink",
        notes.task_note_unlink,
        name="task_note_unlink",
    ),
    # ---- V2-07: GitHub 읽기 (아래는 이 단계에서 추가) ----
    path("orgs/<int:org_id>/discord", discord.org_discord, name="org_discord"),
    path("orgs/<int:org_id>/discord/connect", discord.discord_connect, name="discord_connect"),
    path("orgs/<int:org_id>/discord/unlink", discord.discord_unlink, name="discord_unlink"),
    path("orgs/discord/installed", discord.discord_installed, name="discord_installed"),
    path("orgs/<int:org_id>/issues", github.org_issues, name="org_issues"),
    path("orgs/<int:org_id>/issues/sync", github.org_issues_sync, name="org_issues_sync"),
    path(
        "orgs/<int:org_id>/issues/<int:issue_id>/import",
        github.org_issue_import,
        name="org_issue_import",
    ),
    path("orgs/<int:org_id>/github", github.org_github, name="org_github"),
    path("orgs/<int:org_id>/github/install", github.github_install, name="github_install"),
    path("orgs/github/installed", github.github_installed, name="github_installed"),
    path("settings/github", github.github_connect, name="github_connect"),
    path("settings/github/callback", github.github_callback, name="github_callback"),
    path("settings/github/refresh", github.github_refresh, name="github_refresh"),
    path("settings/github/unlink", github.github_unlink, name="github_unlink"),
    path("projects/<int:project_id>/repo", github.project_repo, name="project_repo"),
    path("projects/<int:project_id>/issues", github.project_issues, name="project_issues"),
    path(
        "projects/<int:project_id>/issues/sync",
        github.project_issues_sync,
        name="project_issues_sync",
    ),
    path(
        "projects/<int:project_id>/issues/<int:issue_id>/import",
        github.project_issue_import,
        name="project_issue_import",
    ),
    path(
        "projects/<int:project_id>/repo/disconnect",
        github.repo_disconnect,
        name="repo_disconnect",
    ),
    path("projects/<int:project_id>/repo/settings", github.repo_settings, name="repo_settings"),
    path(
        "projects/<int:project_id>/repo/issues/sync",
        github.repo_issues_sync,
        name="repo_issues_sync",
    ),
    path(
        "projects/<int:project_id>/repo/issues/<int:number>/import",
        github.repo_issue_import,
        name="repo_issue_import",
    ),
    path(
        "projects/<int:project_id>/repo/events/<int:event_id>/link",
        github.repo_event_link,
        name="repo_event_link",
    ),
    path("tasks/<int:task_id>/git/issue", github.git_issue, name="git_issue"),
    path("tasks/<int:task_id>/git/branch", github.git_branch, name="git_branch"),
    path("tasks/<int:task_id>/git/unlink", github.git_unlink, name="git_unlink"),
    # ---- V2-08: GitHub 쓰기 (아래는 이 단계에서 추가) ----
    path("tasks/<int:task_id>/git/issue/create", github.git_issue_create, name="git_issue_create"),
    path(
        "tasks/<int:task_id>/git/branch/create", github.git_branch_create, name="git_branch_create"
    ),
    path("tasks/<int:task_id>/git/issue/close", github.git_issue_close, name="git_issue_close"),
]
